config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stores#index'
  get 'second', to: 'static_pages#second'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bale.rb
class Bale < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/store_size.rb
class StoreSize < ApplicationRecord
	self.table_name = "store_size" 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def second

end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
		@stores = Store.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<br/>
	<br/>
	<div class="container">
		<div class="row>">
			<div class="col-xs-8">
			  	<div class='top_line'>Individual Performance</div>
			  	<div class='second_line'> Grocery Store Chain - North East Division </div>
			  	<div class='third_line'>May 22 - Jun 19, 2016</div>
			</div>
		  	<div class='logo col-xs-4'> 
		  		<%= image_tag 'logo.jpg' %>
			</div>
		</div>
	</div>
  	
	<br/>
	<br/>




    <%= yield %>
</body>
</html>

app/views/static_pages/second.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<div class="first_headline">PERFORMANCE AGAINST BUDGET </div>
	<br class='clear'/>
	<br/>
	<br/>
	<div class="container">
		<div class="row>">
			<div class="percentage_box col-xs-3 offset-xs-1">
				<div class="percentage">72%</div>
				<div class="percentage_caption">OF BUDGET THIS PERIOD</div>
			</div>
			
			<div class='colummn_one col-xs-3'>
				<%= column_chart [["Actual", 2356],["Budget", 3012]], width: "250px", height: "175px", xtitle: "This Period" %>
			</div>
			
			<div class='colummn_two col-xs-3'>
				<%= column_chart [["Actual", 8396],["Budget", 9102]], width: "250px", height: "175px", xtitle: "Year to Date" %>
			</div>
		</div>
	</div>
	<br class='clear'/>
	<br/>
	<br/>
	<div class="second_headline">PERFORMANCE OVER TIME</div>
	<br class='clear'/>
	<%= line_chart [["2015-01-01", 25000],["2015-02-01", 35000],["2015-03-01", 28000],["2015-04-01", 42000],["2015-05-01", 45000],["2015-06-01", 48000],["2015-07-01", 39000],["2015-08-01", 40000],["2015-09-01", 33000],["2015-10-01", 51000],["2015-11-01", 54000],["2015-12-01", 48000],["2016-01-01", 49000],["2016-02-01", 59000],["2016-03-01", 61000],["2016-04-01", 55000],["2016-05-01", 58000],["2016-06-01", 65000]], width: "700px", height: "300px" %>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>

	<%= link_to 'Page 1', root_path%>

</body>
</html>

app/views/stores/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<table class='col-xs-12'>
		<thead>
			<tr>
				<td class='table_title' colspan="5"> STORE LIST </td>
			</tr>
		</thead>
		<tbody>
			<tr class='first_headers'>
				<th colspan="2">IDENTIFICATION</th>
				<th colspan="2">AMOUNT</th>
				<th>PERFORMANCE</th>
			</tr>
			<tr class='second_headers'>
				<th>DISTRICT</th>
				<th>STORE #</th>
				<th>BALES</th>
				<th>LBS</th>
				<th>PERF SCORE</th>
			</tr>
			<% max_rate = 0 %> 
			<% @stores.each do |st| %> 
				<% store_rate = (st.total_weight/(st.square_feet*0.1)) %>
				<% if store_rate > max_rate %>
					<% max_rate = store_rate %>
				<%end%>
			 <%end%>
			<% @stores.each do |store| %>
				<tr>
					<td> <%= store.district %> </td>
					<td> <%= store.store_number %> </td>
					<td> <%= store.num_bales %> </td>
					<td> <%= store.total_weight %> </td>
					<td>
						<%= (((store.total_weight/(store.square_feet*0.1))/max_rate)*100).round() %>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>

<%= link_to 'Page 2', second_path %>

</body>
</html>  

app/views/stores/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<h1> show </h1>

</body>
</html>